spring:
  #  servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  http:
    encoding: charset=UTF-8

  # datasource 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.130.121.208/sliver_dev
    username: sliver_dev
    password: C6XkjisfT8fZLica
    hikari:
      allow-pool-suspension: true
      auto-commit: true
      maxLifetime: 60000
      idleTimeout: 30000
      minimumIdle: 5
      maximumPoolSize: 10
  # spring security 
  security:
    user:
      name: zhdiwnd
      password: 198105


#WEb_Resource_Path
custom:
  web:
    resource:
      path1: file:./data/post/images/
      path2: file:./data/user/headPortrait/
      path3: file:./data/spotsPicture/
  jwt:
    secretKey: sliverdev
    expirationTime: 604800   #7*24*60*60 7*24h unit:s

  pictureCompress:
    targetSizeKB: 256 
    quality: 0.8 # 0.0 to 1.0

  password:
    passwordMaxLength: 20

  nickName:
    nicknameMaxLength: 10
# Tomcat_Server
server:
  port: 8080
