spring:
#  servlet配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# datasource 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.130.121.208/sliver_dev
    username: sliver_dev
    password: C6XkjisfT8fZLica
    hikari:
      allow-pool-suspension: true
      auto-commit: true
      maxLifetime: 60000
      idleTimeout: 30000
      minimumIdle: 5
      maximumPoolSize: 10
# spring security 安全配置
  security:
    user:
      name: zhdiwnd
      password: 198105
  web:
    resources:
      static-locations: file:D:\Sliver_dev\sliver_server\data\post\images

#资源存放处
custom:
  static:
    resource:
      path1: file:./data/post/images/
      path2: file:./data/user/headPortrait/
# 端口配置
server:
  port: 8080
